palette = "catppuccin_mocha"

[git_status]
disabled = true

[git_metrics]
disabled = true

[shell]
disabled = false
format = '[$indicator]($style)'
# bash_indicator = "bash"
# fish_indicator = "fish"
# zsh_indicator = "zsh"
# powershell_indicator = "pwsh"
# ion_indicator = "ion"
# elvish_indicator = "elvish"
# tcsh_indicator = "tcsh"
# unknown_indicator = "mystery shell"
bash_indicator = "î¯Š"
fish_indicator = "ó°ˆº"
zsh_indicator = "zsh"
powershell_indicator = "ó°¨Š"
# powershell_indicator = "î¯‡"
ion_indicator = "ion"
elvish_indicator = "elvish"
tcsh_indicator = "tcsh"
unknown_indicator = "mystery shell"

[shlvl]
disabled = false
threshold = 1

[status]
disabled = false

[git_commit]
disabled = false
commit_hash_length = 8

[time]
disabled = false

[memory_usage]
disabled = false
#show_percentage = true
#show_swap = true
threshold = -1
style = "bold dimmed green"

[cmd_duration]
min_time = 1

[battery]
disabled = false
format = "[$symbol$percentage]($style) "
full_symbol = "ó°¹ "
charging_symbol = "ó°‚„ "
discharging_symbol = "ó±Ÿ "
unknown_symbol = "ó°‚ƒ "
empty_symbol = "ó°º "

[[battery.display]]
threshold = 99
style = "bold green"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 30
style = "bold orange"

[[battery.display]]
threshold = 10
style = "bold red"

#[custom.shell_not_pwsh]
#command = "echo $0"
#when = """ test "$0" != "pwsh" """

#[custom.shell_pwsh]
#command = "echo pwsh"
#when = "Test-Path $PWD"

[os]
disabled = false
format = "[($symbol $name )]($style)"

[os.symbols]
# Alpaquita = "ğŸ”” "
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "ï…»"
Arch = "ïŒƒ"
Artix = "ïŒŸ"
CentOS = "ïŒ„"
Debian = "ïŒ†"
# DragonFly = "ğŸ‰"
# Emscripten = "ğŸ”—"
EndeavourOS = "ïŒ¢"
Fedora = "ïŒŠ"
FreeBSD = "ïŒŒ"
# Garuda = "ğŸ¦…"
Gentoo = "ïŒ"
# HardenedBSD = "ğŸ›¡ï¸ "
# Illumos = "ğŸ¦"
Linux = "ïŒš"
# Mabox = "ğŸ“¦ "
Macos = "ó°€µ"
Manjaro = "ïŒ’"
# Mariner = "ğŸŒŠ"
# MidnightBSD = "ğŸŒ˜"
Mint = "ó°£­"
# NetBSD = "ğŸš©"
NixOS = "ïŒ“"
OpenBSD = "ïŒ¨"
# OpenCloudOS = "â˜ï¸ "
# openEuler = "ğŸ¦‰"
openSUSE = "ïŒ”"
# OracleLinux = "ğŸ¦´"
Pop = "ïŒª"
Raspbian = "ïŒ•"
Redhat = "ó±„›"
RedHatEnterprise = "ó±„›"
# Redox = "ğŸ§ª"
Solus = "ïŒ­"
SUSE = "ïŒ”"
Ubuntu = "ó°•ˆ"
Unknown = "â“"
# Windows = "ó°–³"
Windows = "ïª²"

[character]
# îš‘
# success_symbol = '[â¯](bold green)'
# error_symbol = '[â¯](bold red)'
# vimcmd_symbol = '[â®](bold green)'
# vimcmd_replace_one_symbol = '[â®](bold purple)'
# vimcmd_replace_symbol = '[â®](bold purple)'
# vimcmd_visual_symbol = '[â®](bold yellow)'
# format = '$symbol '
success_symbol = '[î­°](bold green)'
error_symbol = '[î­°](bold red)'
vimcmd_symbol = '[î­¯](bold green)'
vimcmd_replace_one_symbol = '[î­¯](bold purple)'
vimcmd_replace_symbol = '[î­¯](bold purple)'
vimcmd_visual_symbol = '[î­¯](bold yellow)'
format = '$symbol '

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
